import csv
from pathlib import Path

import pytest

import slab_analyzer


def write_poscar(
    path: Path,
    lattice: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]],
    elements: list[str],
    counts: list[int],
    coordinates: list[tuple[float, float, float]],
    coordinate_mode: str = "Direct",
) -> None:
    lines = [
        "Generated by pytest",
        "1.0",
        " ".join(str(value) for value in lattice[0]),
        " ".join(str(value) for value in lattice[1]),
        " ".join(str(value) for value in lattice[2]),
        " ".join(elements),
        " ".join(str(count) for count in counts),
        coordinate_mode,
    ]
    lines.extend(" ".join(str(value) for value in coordinate) for coordinate in coordinates)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_analyze_direct_structure_outputs_expected_metrics(tmp_path: Path) -> None:
    structure_dir = tmp_path / "slab-a"
    structure_dir.mkdir()
    write_poscar(
        structure_dir / "POSCAR",
        lattice=((3.0, 0.0, 0.0), (0.0, 4.0, 0.0), (0.0, 0.0, 10.0)),
        elements=["Si"],
        counts=[2],
        coordinates=[(0.0, 0.0, 0.2), (0.5, 0.5, 0.4)],
    )

    rows = slab_analyzer.build_summary(tmp_path)

    assert len(rows) == 1
    row = rows[0]
    assert row["folder"] == "slab-a"
    assert row["poscar_path"] == "slab-a/POSCAR"
    assert row["total_atoms"] == 2
    assert row["chemical_formula"] == "Si2"
    assert row["cell_volume"] == pytest.approx(120.0)
    assert row["surface_area"] == pytest.approx(12.0)
    assert row["vacuum_thickness"] == pytest.approx(8.0)


def test_recursive_scan_ignores_root_poscar_and_supports_cartesian(tmp_path: Path) -> None:
    write_poscar(
        tmp_path / "POSCAR",
        lattice=((9.0, 0.0, 0.0), (0.0, 9.0, 0.0), (0.0, 0.0, 9.0)),
        elements=["Ignored"],
        counts=[1],
        coordinates=[(0.0, 0.0, 0.0)],
    )

    nested_dir = tmp_path / "group" / "sample"
    nested_dir.mkdir(parents=True)
    write_poscar(
        nested_dir / "POSCAR",
        lattice=((2.0, 0.0, 0.0), (0.0, 3.0, 0.0), (0.0, 0.0, 12.0)),
        elements=["Al", "O"],
        counts=[2, 1],
        coordinates=[(0.0, 0.0, 11.0), (1.0, 1.5, 1.0), (1.0, 1.5, 3.0)],
        coordinate_mode="Cartesian",
    )

    rows = slab_analyzer.build_summary(tmp_path)

    assert len(rows) == 1
    row = rows[0]
    assert row["folder"] == "group/sample"
    assert row["chemical_formula"] == "Al2O"
    assert row["total_atoms"] == 3
    assert row["cell_volume"] == pytest.approx(72.0)
    assert row["surface_area"] == pytest.approx(6.0)
    assert row["vacuum_thickness"] == pytest.approx(8.0)


def test_main_writes_csv_sorted_by_requested_column(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    structures = [
        ("medium", 2, [(0.0, 0.0, 0.2), (0.0, 0.0, 0.4)]),
        ("small", 1, [(0.0, 0.0, 0.3)]),
        ("large", 3, [(0.0, 0.0, 0.2), (0.0, 0.0, 0.3), (0.0, 0.0, 0.4)]),
    ]
    for folder_name, atom_count, coordinates in structures:
        structure_dir = tmp_path / folder_name
        structure_dir.mkdir()
        write_poscar(
            structure_dir / "POSCAR",
            lattice=((2.0, 0.0, 0.0), (0.0, 2.0, 0.0), (0.0, 0.0, 10.0)),
            elements=["H"],
            counts=[atom_count],
            coordinates=coordinates,
        )

    monkeypatch.chdir(tmp_path)
    exit_code = slab_analyzer.main(["--sort-by", "total_atoms"])

    assert exit_code == 0

    output_path = tmp_path / "slab_summary.csv"
    assert output_path.exists()

    with output_path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    assert [row["folder"] for row in rows] == ["small", "medium", "large"]
    assert [int(row["total_atoms"]) for row in rows] == [1, 2, 3]
    assert rows[0]["chemical_formula"] == "H"
